In [100]:
import numpy as np
import pandas as pd

In [101]:
dataframes = pd.read_csv('data/training_set_metadata.csv')
y = dataframes.target.values
X = np.nan_to_num(dataframes.iloc[:,:11].values)
X_test = np.nan_to_num(pd.read_csv('data/test_set_metadata.csv').values)

In [102]:
### Printing the classes we have in the training dataset.
print(np.unique(y))
print()
print(X_test[:10]) 

[ 6 15 16 42 52 53 62 64 65 67 88 90 92 95]

[[ 1.30000000e+01  3.44531250e+01 -5.22952900e+00  1.69987075e+02
  -5.99561850e+01  1.00000000e+00  3.04800000e-01  3.19300000e-01
   5.42000000e-02  4.11123000e+01  1.90000000e-02]
 [ 1.40000000e+01  3.33984380e+01 -4.33114900e+00  1.67226341e+02
  -5.99365510e+01  1.00000000e+00  0.00000000e+00  6.32300000e-01
   1.79000000e-02  4.28774000e+01  1.80000000e-02]
 [ 1.70000000e+01  3.48529419e+02 -6.17554400e+01  3.21293980e+02
  -5.17633510e+01  1.00000000e+00  0.00000000e+00  8.29700000e-01
   6.05000000e-02  4.36000000e+01  1.60000000e-02]
 [ 2.30000000e+01  3.48046880e+01 -5.82915300e+00  1.71307861e+02
  -6.01744010e+01  1.00000000e+00  0.00000000e+00  6.53300000e-01
   1.47900000e-01  4.29640000e+01  2.30000000e-02]
 [ 3.40000000e+01  3.51321442e+02 -6.41987460e+01  3.17458993e+02
  -5.04299310e+01  1.00000000e+00  4.55700000e-01  4.61700000e-01
   1.22000000e-02  4.20540000e+01  2.30000000e-02]
 [ 3.50000000e+01  3.53320310e+01 -5.979

In [103]:
### Running a SVC classifier using crammer_singer stratigy for multi class classification. 
### NOT recommended according to scikit-learn documentation
from sklearn.svm import LinearSVC

Predictions_SVC_CS = LinearSVC(multi_class="crammer_singer").fit(X, y).predict(X_test)
print(np.unique(Predictions_SVC_CS))

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[16 42 64 65 88 90 92]


In [98]:
### Running a SVC classifier using One_VS_Rest stratigy for multi class classification. 

#from sklearn.multiclass import OneVsRestClassifier
#PredictionsOVR = OneVsRestClassifier(LinearSVC(random_state=0), -1).fit(X, y).predict(X_test) 
#print(np.unique(PredictionOVO))

Predictions_SVC_OVR = LinearSVC(multi_class="ovr").fit(X, y).predict(X_test)
print(np.unique(Predictions_SVC_OVR))

/opt/conda/lib/python3.6/site-packages/sklearn/svm/base.py:931: ConvergenceWarning: Liblinear failed to converge, increase the number of iterations.
  "the number of iterations.", ConvergenceWarning)


[42 65 90 92]


In [3]:
unique_objects = np.unique(df.object_id)

In [99]:
### Running a OneVsOneClassifier classifier using LinearSVC as the estimator.
from sklearn.multiclass import OneVsOneClassifier

X_test = X_test[0:500000,:] ### Doesn't work with the whole test set. TODO: Figure out why!
PredictionOVO = OneVsOneClassifier(LinearSVC(random_state=0), -1).fit(X, y).predict(X_test) 
print(np.unique(PredictionOVO))

[16 42 65 67 88 90 92]
